name: Translate CSV to Spanish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Clone repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Bước 2: Thiết lập Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Bước 3: Cài đặt thư viện cần thiết
    - name: Install dependencies
      run: |
        pip install pandas openai

    # Bước 4: Chạy script Python để dịch file CSV
    - name: Run translation script
      run: python translate_csv.py

    # Bước 5: Tải file đã dịch lên Artifacts
    - name: Upload translated file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: translated-csv
        path: spanish_translated.csv
